### PR TITLE
CASMCMS-8651: Remove ARS from CLI; Use updated BSS API spec with updated non-ARS link examples

### PR DESCRIPTION
**Pull request by mharding-hpe**
### Summary and Scope

- Fixes: [CASMCMS-8651](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8651)

#### Issue Type

- RFE Pull Request

ARS has been gone for a long time. It was left in the CLI temporarily as services transitioned away from it. None of this leftover code is required any longer. This PR removes it.

The BSS API spec also had an old outdated reference to ARS in a couple example strings. This has been corrected in the BSS API spec and this PR updates the CLI to use the new spec.

### Prerequisites

- [X] I have included documentation in my PR (or it is not required)

I ran the unit tests and no errors were encountered.
 
### Risks and Mitigations

Low risk -- ARS has been gone for a LONG time.

### CODE REVIEW

**Review by mjendrysik-hpe — APPROVED** [review]

**Review by mjendrysik-hpe — APPROVED** [review]

**Review by dlaine-hpe — APPROVED** [review]

**Review by shunr-hpe — APPROVED** [review]

**Comment by mharding-hpe** [comment]
The hms-bss PR has merged, so this guy is also ready to be merged.

**Comment by mharding-hpe** [comment]
@erl-hpe @rustydb Can you merge this badboy when you have the chance? It is ready.

**Review by rbak-hpe — APPROVED** [review]

**Comment by mharding-hpe** [comment]
@rustydb would love to get this badboy merged today, if possible.

**Comment by rustydb** [comment]
> @rustydb would love to get this badboy merged today, if possible.

I pinged CASMPET, inquiring for their stamp and whether they should remain a code owner.

**Review by kburns-hpe — APPROVED** [review]

**Pull request merged**
