### PR TITLE
CASMCLOUD-1220: Language linting and minor corrections

### PR DESCRIPTION
**Pull request by mharding-hpe**
### Summary and Scope

- Fixes: [CASMCLOUD-1220](https://jira-pro.it.hpe.com:8443/browse/CASMCLOUD-1220)

#### Issue Type

- Bugfix Pull Request
- Docs Pull Request

Minor language linting, mostly to markdown and code comments. In a couple of cases the capitalization within some usage messages is changed. No functional changes.

### Prerequisites

- [X] I have included documentation in my PR (or it is not required)

### Idempotency
 

No code changes.
 
### Risks and Mitigations
 

Very low risk. Just language linting. To make sure I did not accidentally introduce some formatting or syntax error to any of the source files, I did run the unit tests and make sure that they still passed.

### CODE REVIEW

**Review by mjendrysik-hpe — APPROVED** [review]

**Review by rustydb — APPROVED** [review]

**Comment by mharding-hpe** [comment]
I don't understand what is causing the unit test failures in the PR checks -- when I manually run the unit tests using Python 3.10 following the markdown docs in the repo, they pass. And as you can see from what this PR is changing, it shouldn't be resulting in the number and type of errors being shown in the PR unit test failures. Is there some known problem with that check in the repo?

**Comment by mharding-hpe** [comment]
Ok, this time 3.10 unit tests worked, so it looks like an intermittent failure. I'll try rerunning it on all of the PRs and see if any errors persist and appear to be genuine (but since I ran them manually, like I said, I'm assuming this will not be the case)

**Comment by mharding-hpe** [comment]
This badboy is ready to be merged by someone with the necessary authority.

**Review by mtupitsyn — APPROVED** [review]

**Comment by mharding-hpe** [comment]
@erl-hpe @rustydb Can you merge this badboy when you have the chance? It is ready.

**Comment by mharding-hpe** [comment]
@rustydb would love to get this badboy merged today, if possible.

**Review by kburns-hpe — APPROVED** [review]

**Pull request merged**
