### PR TITLE
CASMHMS-5903: Update power-capping API spec

### PR DESCRIPTION
**Pull request by mharding-hpe**
## Summary and Scope

The spec file used in this repo has fallen behind the one in its source repository. This PR brings it up to date.

Functionally there should be no difference (apart from some of the text strings).

## Issues and Related PRs

* [power-control repository PR](https://github.com/Cray-HPE/hms-power-control/pull/23) -- merged!

## Testing

{noformat}
# nox -s tests cover
nox > Running session tests

...

nox > Session cover was successful.
nox > Ran multiple sessions:
nox > * tests: success
nox > * cover: success
{noformat}

## Risks and Mitigations

Low risk -- no functional changes.

## Pull Request Checklist

- [X] Version number(s) incremented, if applicable
- [X] Copyrights updated
- [X] License file intact
- [X] Target branch correct
- [X] Testing is appropriate and complete, if applicable
- [X] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Review by mjendrysik-hpe — CHANGES_REQUESTED** [review]
The swagger3.json can only have the Description, tags and servers. The paths must be empty.

**Review by mjendrysik-hpe — CHANGES_REQUESTED** [review]
I don't think the swagger.yaml file can exist there either. If it does I believe the swagger3.json file is automatically created. Which would be bad.

**Review by erl-hpe — DISMISSED** [review]

**Comment by mharding-hpe** [comment]
I've added a commit to address the comments from @mjendrysik-hpe. I'm going to re-run the nox test suite now, to make sure it's still happy. I'll comment when that's done, @erl-hpe .

Michael, one thing that I am curious about -- other than a possible performance penalty, shouldn't the tests have caught it if this was going to break anything?

**Comment by mharding-hpe** [comment]
> I don't think the swagger.yaml file can exist there either. If it does I believe the swagger3.json file is automatically created. Which would be bad.

Hmmm, I wasn't aware of that behavior. The docs in the repo give instructions on how to generate the JSON file from your YAML file, so I assumed it was something that had to be done ahead of time. I didn't get the impression that the YAML files were actually used by the CLI. I saw that a lot of other components had them included, and I figured it was just there as a reference as to which YAML file was used to generate the JSON file.

The other reason I thought that, I guess, is that every module I checked had a JSON file too. If the JSON was auto-generated from the YAML, then I would have thought there'd be no reason to check in the JSON.

But I am not an expert on the CLI, and in this case, it's easy enough to remove the YAML file from the PR. But I will do some experiments after this to find out the actual behavior, for future reference.

**Comment by mharding-hpe** [comment]
nox tests all still pass -- looks good from my perspective.

**Comment by mjendrysik-hpe** [comment]
> The other reason I thought that, I guess, is that every module I checked had a JSON file too. If the JSON was auto-generated from the YAML, then I would have thought there'd be no reason to check in the JSON.

That may be true but for some reason I seem to remember magic like that happening at one point.

**Review by mjendrysik-hpe — APPROVED** [review]

**Review by erl-hpe — APPROVED** [review]

**Pull request merged**
